# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download

builds:
  - id: "go-bookstore"
    main: ./src/main.go
    env:
      # - GOOS=linux
      # - GOARCH=amd64
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: "archive-go-bookstore"
    name_template: "authc_{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    builds: # Builds reference which build instances should be archived in this archive.
      - "goapp"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    allow_different_binary_count: true

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'