---
repositories:
  - name: devopscorner-lab
    url: s3://devopscorner-helm-chart/lab

templates:
  default: &default
    namespace: devops-tools
    version: "1.4.0-rc"

releases:
  - name: bookstore-rest
    chart: devopscorner-lab/api
    values:
      - ./api-rest-values.yml
    <<: *default

  - name: bookstore-grpc
    chart: devopscorner-lab/api
    values:
      - ./api-grpc-values.yml
    <<: *default