apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookstore
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/devopscorner/golang-deployment.git
    path: manifests
    targetRevision: HEAD
  destination:
    server: https://your-kubernetes-server
    namespace: bookstore
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
  healthChecks:
    - type: DeploymentRollout
      deploymentName: bookstore-deployment
  ignoreDifferences:
    - kind: Service
      jsonPointers:
        - /spec/clusterIP
    - kind: Deployment
      jsonPointers:
        - /spec/selector/matchLabels
  appVersion: ${VERSION}
